name: DumbosRadio

options:
  bundleIdPrefix: com.miles
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15"
  generateEmptyDirectories: true
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual
    CLANG_ENABLE_MODULES: YES

targets:
  DumbosRadio:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: DumbosRadio
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.miles.NotMyFirstRadio
        PRODUCT_NAME: "Not My First Radio"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        INFOPLIST_FILE: DumbosRadio/Info.plist
        CODE_SIGN_ENTITLEMENTS: DumbosRadio/DumbosRadio.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/../Frameworks
        SWIFT_STRICT_CONCURRENCY: minimal
        ENABLE_PREVIEWS: YES
    dependencies:
      - sdk: AVFoundation.framework
      - sdk: MediaPlayer.framework
      - sdk: MediaToolbox.framework
      - sdk: Accelerate.framework
      - sdk: ServiceManagement.framework
      - sdk: UserNotifications.framework
    info:
      path: DumbosRadio/Info.plist
      properties:
        LSApplicationCategoryType: public.app-category.music
        NSUserNotificationAlertStyle: alert
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        LSUIElement: false
        CFBundleIconFile: AppIcon
        CFBundleName: NMFR
        CFBundleDisplayName: "Not My First Radio"
    entitlements:
      path: DumbosRadio/DumbosRadio.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-write: true

schemes:
  DumbosRadio:
    build:
      targets:
        DumbosRadio: all
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.SQLDebug": "0"
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
